
export const Courses =[
  {
    "id":1,
    "course_name":'All Courses',
    "course_link":"https://courses.microdegree.work/pages/premium-courses",
    "course_desc":"Master AWS & DevOps from Cloud industry experts to become a solid Computing Professional",
    "course_category":'programming',
    "course_price":'20,000',
    "course_status":['live'],
    course_details:["60 Hrs of LIVE Online Training",
    "Concepts Explained in Kannada",
    "Completion Certificate",
    "Build Interactive Projects",
    "Doubt Clarification",
    "Interview Preparation",
    "Career Assistance",
  ],
},
  {
      "id":2,
      "course_name":'Aws & DevOps Certification',
      "course_img":"https://ik.imagekit.io/microdegree/Course_Images/AWSDevOpsCertification_JPPM3QVHYS_.png?ik-sdk-version=javascript-1.4.3&updatedAt=1661163836359",
      "course_link":"https://courses.microdegree.work/courses/aws-developer-certification-live",
      "course_desc":"Master AWS & DevOps from Cloud industry experts to become a solid Computing Professional",
      "course_category":'programming',
      "course_price":'20,000',
      "course_status":['live'],
      course_details:["60 Hrs of LIVE Online Training",
      "Concepts Explained in Kannada",
      "Completion Certificate",
      "Build Interactive Projects",
      "Doubt Clarification",
      "Interview Preparation",
      "Career Assistance",
    ],
  },
  {
      "id":3,
      "course_name":'Aws Devops Pre-Recorded',
      "course_img":"https://ik.imagekit.io/microdegree/Course_Images/AWSDevOps11_bkQbtt1aKi.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1661163836101",
      "course_link":"https://courses.microdegree.work/bundles/aws-devops",
      "course_desc":"Learn AWS & DevOps with our Industry Experts and Become a Solid Cloud Professional in 60 Hours",
      "course_category":'programming',
      "course_price":'6,500',
      "course_status":['live'],
      course_details:["60 Hrs of LIVE Online Training",
      "Concepts Explained in Kannada",
      "Completion Certificate",
      "Build Interactive Projects",
      "Doubt Clarification",
      "Interview Preparation",
      "Career Assistance",
    ],
  },
  {
    "id":4,
    "course_name":'Full Stack Web Development Certification',
    "course_img":"https://ik.imagekit.io/microdegree/Course_Images/webDev_Sauu6SRWUHA.png?ik-sdk-version=javascript-1.4.3&updatedAt=1661163836220",
    "course_link":"https://courses.microdegree.work/courses/full-stack-web-development-certification",
    "course_desc":"Start with Basic HTML untill advanced Server Side Concepts with NodeJs & MongoDB to become a Expert MERN Stack Developer",
    "course_category":'programming',
    "course_price":'7,500',
    "course_status":['live'],
    course_details:["60 Hrs of LIVE Online Training",
    "Concepts Explained in Kannada",
    "Completion Certificate",
    "Build Interactive Projects",
    "Doubt Clarification",
    "Interview Preparation",
    "Career Assistance",
  ],
},
  {
      "id":5,
      "course_name":'Microdegree pro',
      "course_img":"https://ik.imagekit.io/microdegree/Course_Images/JavaSalenium_Wq1dtjtuA-.png?ik-sdk-version=javascript-1.4.3&updatedAt=1661163836083",
      "course_link":"https://pages.razorpay.com/pl_Gev62ka8kgBbte/view",
      "course_desc":"Get Pro subscription and access unlimited course access on platform",
      "course_category":'programming',
      "course_price":'3,000',
      "course_status":['live'],
      course_details:["60 Hrs of LIVE Online Training",
      "Concepts Explained in Kannada",
      "Completion Certificate",
      "Build Interactive Projects",
      "Doubt Clarification",
      "Interview Preparation",
      "Career Assistance",
    ],
  },
  {
    "id":6,
    "course_name":'Data Science Weekend Live',
    "course_img":"https://ik.imagekit.io/microdegree/Course_Images/FullStackData11_ZjiHeWOtVX.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1661163835809",
    "course_link":"https://courses.microdegree.work/courses/full-stack-data-science-certification",
    "course_desc":"Start with Basic Python until advanced Visualization Concepts with Power Bi to become a Data Science Expert",
    "course_category":'programming',
    "course_price":'7,500',
    "course_status":['live'],
    course_details:["60 Hrs of LIVE Online Training",
    "Concepts Explained in Kannada",
    "Completion Certificate",
    "Build Interactive Projects",
    "Doubt Clarification",
    "Interview Preparation",
    "Career Assistance",
  ],
},
  {
      "id":7,
      "course_name":'React js',
      "course_img":"https://ik.imagekit.io/microdegree/Course_Images/ReactJS_AXgaxluRTp6.png?ik-sdk-version=javascript-1.4.3&updatedAt=1661163836535",
      "course_link":"https://courses.microdegree.work/courses/react",
      "course_desc":"Learn React from scratch, build real-world project and get ready to be a solid Frontend Developer",
      "course_category":'programming',
      "course_price":'949',
      "course_status":['live'],
      course_details:["60 Hrs of LIVE Online Training",
      "Concepts Explained in Kannada",
      "Completion Certificate",
      "Build Interactive Projects",
      "Doubt Clarification",
      "Interview Preparation",
      "Career Assistance",
    ],
  },
  {
    "id":8,
    "course_name":'Python Certification',
    "course_img":"https://ik.imagekit.io/microdegree/Course_Images/Python_vWkoh4U97Dj.png?ik-sdk-version=javascript-1.4.3&updatedAt=1661163836461",
    "course_link":"https://courses.microdegree.work/courses/python",
    "course_desc":"Learn Python from scratch and build interactve projects. Kick-start your journey into the world of Data Science and Machine Learning here.",
    "course_category":'programming',
    "course_price":'949',
    "course_status":['live'],
    course_details:["60 Hrs of LIVE Online Training",
    "Concepts Explained in Kannada",
    "Completion Certificate",
    "Build Interactive Projects",
    "Doubt Clarification",
    "Interview Preparation",
    "Career Assistance",
  ],
},
{
  "id":9,
  "course_name":'MySQL Certification',
  "course_img":"https://ik.imagekit.io/microdegree/Course_Images/MySQL_o0JnXmAg1KT.png?ik-sdk-version=javascript-1.4.3&updatedAt=1661163836321",
  "course_link":"https://courses.microdegree.work/courses/mysql",
  "course_desc":"Learn Python from scratch and build interactve projects. Kick-start your journey into the world of Data Science and Machine Learning here.",
  "course_category":'programming',
  "course_price":'949',
  "course_status":['live'],
  course_details:["60 Hrs of LIVE Online Training",
  "Concepts Explained in Kannada",
  "Completion Certificate",
  "Build Interactive Projects",
  "Doubt Clarification",
  "Interview Preparation",
  "Career Assistance",
],
},

]